"""
PDF transcript export using reportlab.

Generates a polished, readable PDF with bold speaker names, timestamps,
and the same text processing pipeline as the TXT export.
"""

import io

from reportlab.lib.enums import TA_CENTER, TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
)
from reportlab.lib.colors import Color

from app.routers.segments import (
    _capitalize_first,
    _capitalize_sentences,
    _clean_fillers,
    _fmt_display_time,
    _format_phone_numbers,
    _group_by_speaker,
    _INCOMPLETE_TRAIL_WORDS,
    _is_trivial,
    _SHORT_CONTINUATION,
    _speaker_name,
    _split_paragraphs,
)

# ── Colours ──────────────────────────────────────────────────────────────────

_GRAY = Color(0.45, 0.45, 0.45)
_LIGHT_GRAY = Color(0.6, 0.6, 0.6)
_RULE_GRAY = Color(0.75, 0.75, 0.75)

# ── Styles ───────────────────────────────────────────────────────────────────

_styles = getSampleStyleSheet()

_STYLE_TITLE = ParagraphStyle(
    "PdfTitle",
    parent=_styles["Normal"],
    fontName="Helvetica-Bold",
    fontSize=16,
    leading=20,
    spaceAfter=4,
)

_STYLE_META = ParagraphStyle(
    "PdfMeta",
    parent=_styles["Normal"],
    fontName="Helvetica",
    fontSize=10,
    leading=13,
    textColor=_GRAY,
)

_STYLE_META_ITALIC = ParagraphStyle(
    "PdfMetaItalic",
    parent=_styles["Normal"],
    fontName="Helvetica-Oblique",
    fontSize=10,
    leading=13,
    textColor=_GRAY,
)

_STYLE_SPEAKER = ParagraphStyle(
    "PdfSpeaker",
    parent=_styles["Normal"],
    fontName="Helvetica-Bold",
    fontSize=12,
    leading=16,
    spaceBefore=16,
    spaceAfter=2,
)

_STYLE_BODY = ParagraphStyle(
    "PdfBody",
    parent=_styles["Normal"],
    fontName="Helvetica",
    fontSize=11,
    leading=14,
    spaceBefore=0,
    spaceAfter=6,
)

_STYLE_FOOTER_CENTER = ParagraphStyle(
    "PdfFooterCenter",
    parent=_styles["Normal"],
    fontName="Helvetica",
    fontSize=8,
    textColor=_LIGHT_GRAY,
    alignment=TA_CENTER,
)

_STYLE_FOOTER_RIGHT = ParagraphStyle(
    "PdfFooterRight",
    parent=_styles["Normal"],
    fontName="Helvetica",
    fontSize=7,
    textColor=_LIGHT_GRAY,
    alignment=TA_RIGHT,
)


# ── XML-escape for reportlab paragraphs ──────────────────────────────────────

def _esc(text: str) -> str:
    """Escape text for use inside reportlab Paragraph XML markup."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


# ── Footer template ─────────────────────────────────────────────────────────

class _FooterTemplate:
    """Draws page number and branding on every page."""

    def __init__(self):
        self.page_count = 0

    def on_page(self, canvas, doc):
        self.page_count = max(self.page_count, doc.page)
        canvas.saveState()
        # Page N — centered
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(_LIGHT_GRAY)
        page_text = f"Page {doc.page}"
        canvas.drawCentredString(
            doc.pagesize[0] / 2, 0.5 * inch, page_text
        )
        # Branding — right
        canvas.setFont("Helvetica", 7)
        canvas.drawRightString(
            doc.pagesize[0] - inch, 0.5 * inch, "Generated by Civic Media"
        )
        canvas.restoreState()

    def on_page_later(self, canvas, doc):
        self.on_page(canvas, doc)


# ── Text processing (mirrors _to_txt logic) ─────────────────────────────────

def _build_turn_paragraphs(valid_segments: list) -> list[str]:
    """
    Join segments into paragraphs with the same punctuation/splitting
    logic used by the TXT export.
    """
    # 1. Split into natural groups at >2s silence gaps
    natural_groups: list[list[str]] = []
    current: list[str] = []
    for i, seg in enumerate(valid_segments):
        text = seg.text.strip()
        if not text:
            continue
        if i > 0 and current:
            gap = seg.start_time - valid_segments[i - 1].end_time
            if gap > 2.0:
                natural_groups.append(current)
                current = []
        current.append(text)
    if current:
        natural_groups.append(current)

    # 2. Within each natural group, join with punctuation logic
    joined_groups: list[str] = []
    for seg_texts in natural_groups:
        joined = ""
        for j, t in enumerate(seg_texts):
            if j == 0:
                joined = t
                continue
            prev_has_punct = joined and joined[-1] in ".?!"
            prev_is_short = len(joined) < 30
            is_substantial = len(t) >= _SHORT_CONTINUATION
            if prev_has_punct:
                joined += " " + _capitalize_first(t)
            elif is_substantial and not prev_is_short:
                joined += ". " + _capitalize_first(t)
            else:
                joined += " " + t

        joined = _clean_fillers(joined)
        joined = _capitalize_first(joined)
        joined = _capitalize_sentences(joined)
        joined = _format_phone_numbers(joined)
        joined_groups.append(joined)

    # 3. Split long groups into paragraphs
    all_paragraphs: list[str] = []
    for text in joined_groups:
        all_paragraphs.extend(_split_paragraphs(text))

    # 4. Trailing period logic
    if all_paragraphs:
        last = all_paragraphs[-1]
        if last and last[-1] not in ".?!":
            final_word = last.rstrip().split()[-1].lower().strip(".,;:'\"")
            if final_word not in _INCOMPLETE_TRAIL_WORDS:
                all_paragraphs[-1] = last + "."

    return all_paragraphs


# ── Public API ───────────────────────────────────────────────────────────────

def generate_transcript_pdf(segments: list, meeting) -> bytes:
    """
    Build a polished PDF transcript and return it as bytes.

    Args:
        segments: list of TranscriptSegment ORM objects (with assignment loaded)
        meeting: Meeting ORM object
    """
    buf = io.BytesIO()
    footer = _FooterTemplate()

    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=inch,
        rightMargin=inch,
        topMargin=inch,
        bottomMargin=0.85 * inch,
    )

    story: list = []

    # ── Header ───────────────────────────────────────────────────────────
    if meeting:
        story.append(Paragraph(_esc(meeting.title), _STYLE_TITLE))

        meta_parts = []
        if meeting.meeting_date:
            meta_parts.append(str(meeting.meeting_date))
        if hasattr(meeting, "governing_body") and meeting.governing_body:
            meta_parts.append(meeting.governing_body)
        if meta_parts:
            story.append(Paragraph(_esc(" — ".join(meta_parts)), _STYLE_META))

        # Speaker list
        speakers, seen = [], set()
        for seg in segments:
            name = _speaker_name(seg)
            if name not in seen and name not in ("Unknown", "unnamed speaker"):
                seen.add(name)
                speakers.append(name)
        if speakers:
            story.append(
                Paragraph(
                    "Speakers: " + _esc(", ".join(speakers)),
                    _STYLE_META_ITALIC,
                )
            )

        story.append(Spacer(1, 8))
        story.append(HRFlowable(width="100%", thickness=0.5, color=_RULE_GRAY))
        story.append(Spacer(1, 4))

    # ── Body — speaker turns ─────────────────────────────────────────────
    for group in _group_by_speaker(segments):
        valid = [s for s in group["segments"] if not _is_trivial(s.text)]
        if not valid:
            continue

        timestamp = _fmt_display_time(valid[0].start_time)
        speaker = group["speaker"]

        # Speaker line: "Name" bold + timestamp in gray
        speaker_markup = (
            f'<b>{_esc(speaker)}</b>'
            f' <font size="10" color="#737373">{_esc(timestamp)}</font>'
        )
        story.append(Paragraph(speaker_markup, _STYLE_SPEAKER))

        # Body paragraphs
        paragraphs = _build_turn_paragraphs(valid)
        for para in paragraphs:
            story.append(Paragraph(_esc(para), _STYLE_BODY))

    # ── Build PDF ────────────────────────────────────────────────────────
    doc.build(
        story,
        onFirstPage=footer.on_page,
        onLaterPages=footer.on_page_later,
    )

    return buf.getvalue()
